/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_Demo */

#ifndef _Included_com_jiage_Demo
#define _Included_com_jiage_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_Demo
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jiage_Demo_set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiage_Demo
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_Demo_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
